

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    container_name: nepali-fastapi

  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run /app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0 --server.enableCORS=false
    volumes:
      - .:/app
    container_name: nepali-streamlit
    depends_on:
      - fastapi
